### ISSUE TITLE
Instructions contain multiple errors

### ISSUE THREAD

**Issue by conduit242** [twitter-research/tgn#10]
The instructions and README contain multiple errors.
1. The referenced 'reddit' and 'wikipedia' datasets don't exist. The temporal graph datasets related to these names found at the site are: 'soc-RedditHyperlinks' and 'wiki-talk-temporal'.
2. The linked datasets are not csv files as described.
3. The linked datasets do not have the label column required by the preprocessing script.
4. The linked datasets have radically different node and edge counts than are listed in the paper.

Kumar et al's paper does not provide the datasets either. They state:
"Reddit post dataset: this public dataset consists of one month
of posts made by users on subreddits [2]. We selected the 1,000
most active subreddits as items and the 10,000 most active users.
This results in 672,447 interactions. We convert the text of each
post into a feature vector representing their LIWC categories [35]"
"Wikipedia edits: this public dataset is one month of edits made
by edits on Wikipedia pages [3]. We selected the 1,000 most edited
pages as items and editors who made at least 5 edits as users (a total
of 8,227 users). This generates 157,474 interactions. Similar to the
Reddit dataset, we convert the edit text into a LIWC-feature vector"

Please include or link to the exact datasets used in the paper for reproducibility.

**Comment by pc2005** [comment]
Maybe they have updated:
http://snap.stanford.edu/jodie/wikipedia.csv
http://snap.stanford.edu/jodie/reddit.csv

**Comment by lukashina** [comment]
The instructions worked for me
