### ISSUE TITLE
About twitter datasets

### ISSUE THREAD

**Issue by BlackHorseQ** [twitter-research/tgn#11]
hello dear authors, would you like to tell me where  I can get twitter dataset. thanks!

**Comment by emalgorithm** [comment]
Hi @BlackHorseQ,

We describe how to generate the Twitter dataset in appendix A.3 of our [arxiv paper](https://arxiv.org/abs/2006.10637). Unfortunately, due to privacy reasons, we are not able to directly share the dataset with the public.
