### ISSUE TITLE
How do you ensure that a randomly selected negative sample does not happen to be a destination?

### ISSUE THREAD

**Issue by fireindark707** [twitter-research/tgn#13]
Thank you for this study and the scripts. I think it is a great contribution to the study of dynamic graph.

But when I was reading the Code, I found a problem that I thought about for a long time but couldn't understand. I suspect that this may affect the effectiveness of the model evaluation. During the generation of negatives_batch, I noticed that the RandEdgeSampler randomly selects a batch of destination nodes as negative samples for calculation. But what if the samples that happen to be selected are the ones that has an edge with the source node?

Perhaps when there are enough nodes, this will not cause a problem. But I'm still curious as to why you don't avoid this problem. (Exclude in random selection)

Thanks

**Comment by ZulunZhu** [comment]
Yes, I also found this problem. A random sample and sorting them can not ensure they are all negative samples.

**Comment by emalgorithm** [comment]
Hi @fireindark707,

That is a good point. We assume that given the fairly large number of nodes in the datasets we use, the probability of getting a true destination as negative is extremely low. However, as you point out, it could be wise to check this explicitly.
