### ISSUE TITLE
Why updating memory during testing phase ?

### ISSUE THREAD

**Issue by yeeeqichen** [twitter-research/tgn#15]
As the title suggests, I think data in test-set shouldn't be used for updating the model's memory. In your implementation, you updates the model's memory with the positive triples' information:

`      # Persist the updates to the memory only for sources and destinations (since now we have
        # new messages for them)
        self.update_memory(positives, self.memory.messages)
`

But in fact, while testing in real-world scene, the data is unlabeled so we have no idea whether the triple is positive or not.

**Comment by emalgorithm** [comment]
Hi @yeeeqichen,

The idea is that at test time (eg. after deployment) the model will observe new interactions, and wants to incorporate them into the memory. Let's say the model is trying to predict with which tweet I will engage. When I will later engage with a tweet, regardless of whether the model prediction was correct or not, the model now observes new ground truth data (the actual interaction I made), and can incorporate that into the memory (and doing this will be useful to predict my future interactions).

Does this answer your question?

**Comment by yeeeqichen** [comment]
@emalgorithm, Thank you for your reply!

Now I understand the idea of incorporating new interactions after deployment. Indeed, the actual interaction could be observed later in some scenarios(e.g. tweet). I just worried that the comparison between TGN and other methods that don't make use of the assumption that viewing the triplet in test set as observable ground truth could be a little bit unfair. But it's cool that TGN could do a good job under this assumption!

By the way, now I do realize that this assumption is reasonable, and making use of this assumption is a good idea!

Thank you again for your effort!
