### ISSUE TITLE
Time is not considered when predicting new interactions

### ISSUE THREAD

**Issue by naman-ali** [twitter-research/tgn#18]
I modified the test function to evaluate if changing time impacts the predictions, and it does not.

Here is the way I did it:

For a specific pair of src and dst, I created multiple interactions having different timesteps, and the predictions are all equal probabilities. Basically changing time does nothing.

I am now confused about the entire idea of the paper. What is the goal of TGN? Is the goal just to predict future destinations without time?

**Comment by emalgorithm** [comment]
Hi @naman-ali,

Thanks for the interesting finding. While the idea of the TGN model is to have time-dependent predictions, and is in theory able to do so thanks to the time encoding, the current available datasets (and tasks) probably don't require to learn a sophisticated time-dependent function to make predictions, but it's probably enough to know what happened in the past to predict what will immediately happen next to obtain excellent performance.

I agree that having more interesting datasets (and tasks) would be important for the field.

**Comment by phucdoitoan** [comment]
> For a specific pair of src and dst, I created multiple interactions having different timesteps, and the predictions are all equal probabilities. Basically changing time does nothing.

@naman-ali How did you modify the test function? 
I tested on the Wikipedia datasets and got different probabilities for different timesteps.

**Comment by naman-ali** [comment]
@phucdoitoan You can modify it by creating multiple records for each specific pair (src, dst) but changing the timesteps. Another way you can test is to set a constant value for all of the test interactions times, and you should get similar results.
