### ISSUE TITLE
Twitter dataset

### ISSUE THREAD

**Issue by KristenMoore** [twitter-research/tgn#2]
Hi,
I'm wondering how to reproduce the future edge prediction results from your work for the Twitter dataset from the 2020 RecSys Challenge. 
If I want to create a dataset similar to what you've described in the paper, should I format the data with the same columns as Reddit and Wikipedia, and then run the preprocessing script with bipartite=False?
Are there any other tips you can give me on necessary changes for training the model?
Thanks a lot.

**Comment by KimMeen** [comment]
I have the same question that does the Twitter dataset mentioned in the paper will be open-sourced to reproduce the experiments?

**Comment by emalgorithm** [comment]
We cannot release the dataset, however in the new version of the paper, section A.3 of the Appendix, we explain how to generate an updated version of it:

> To generate the Twitter dataset we started with the snapshot of the
> Recsys Challenge training data on 2020/09/06. We filtered the data to include only retweet edges
> (discarding other types of interactions) where the timestamp was present. This left approximately
> 10% of the edges in the original dataset. We then filtered the retweet multi-graph (users can be
> connected by multiple retweets) to only include the largest connected component. Finally, we filtered
> the graph to only the top 5,000 nodes in-degree and the top 5,000 by out-degree, ending up with 8,861
> nodes since some nodes were in both sets

We also now changed the `preprocess_data.py` file so that it is enough to leave out the `--bipartite flag` when processing non-bipartite graphs.
