### ISSUE TITLE
How to make predictions with TGN?

### ISSUE THREAD

**Issue by moudheus** [twitter-research/tgn#22]
Hi @emalgorithm ,

Thanks for the interesting work.

I want for each user in the training set to predict the top K training items they are most likely to interact with at future time T.

Here is what I did, please let me know if I got something wrong:

1. Trained TGN with memory with tgn/train_self_supervised.py
1. Using the trained TGN to compute embeddings for all training users and all training items using tgn.embedding_module.compute_embedding. I am using the memory and time differences between last update of each node and T.
3. For each user use tgn.affinity_score to compute the affinity with all items and select the TOP K

Does it seem correct? I can share the code, it is short.

Thank you
Marc

**Comment by emalgorithm** [comment]
Hi @moudheus, that does seem correct to me!

**Comment by peg-repo** [comment]
Hi @moudheus.
I wonder you can share the code about making prediction with TGN??
Thank u :)

**Comment by vanoudh** [comment]
Hi @soyoung1452 sorry for the delay, it is here : https://github.com/vanoudh/tgn/blob/master/predict.py
