### ISSUE TITLE
Errors while  running train_self_supervised.py

### ISSUE THREAD

**Issue by lumen2018** [twitter-research/tgn#6]
When running the  train_self_supervised.py on the Reddit dataset, I always got the followings errors:

Traceback (most recent call last):
  File "train_self_supervised.py", line 221, in <module>
    timestamps_batch, edge_idxs_batch, NUM_NEIGHBORS)
  File "/home/scg/tgn-master/model/tgn.py", line 211, in compute_edge_probabilities
    source_nodes, destination_nodes, negative_nodes, edge_times, edge_idxs, n_neighbors)
  File "/home/scg/tgn-master/model/tgn.py", line 166, in compute_temporal_embeddings
    "Something wrong in how the memory was updated"
AssertionError: Something wrong in how the memory was updated

And, can I annotate  "      assert torch.allclose(memory[positives], self.memory.get_memory(positives), atol=1e-5), \
        "Something wrong in how the memory was updated"  in tgn.py     " .  Thank you very much.

**Comment by erfanloghmani** [comment]
Same problem here!

Did you find the problem or any workarounds?

**Comment by emalgorithm** [comment]
It's a numerical issue which I don't really understand why it happens, but I guess you can just comment out that assertion and the code should run.

**Comment by lumen2018** [comment]
> It's a numerical issue which I don't really understand why it happens, but I guess you can just comment out that assertion and the code should run.

Thank you very much, when I comment out that assertion, it runs now.  Note that the problem only occurs on the Reddit dataset.
