### ISSUE TITLE
What is the difference between memory_update_at_start=False and True?

### ISSUE THREAD

**Issue by wangywUST** [twitter-research/tgn#8]

**Comment by Ericcsr** [comment]
Same question here; from code it seems that the update memory at start will use previous messages on current node, which only uses part of the previous batched messages potentially. And update at the end will use current message on current node after the embedding. But will there be any performance issue or concern?

**Comment by dwang55** [comment]
> Same question here; from code it seems that the update memory at start will use previous messages on current node, which only uses part of the previous batched messages potentially. And update at the end will use current message on current node after the embedding. But will there be any performance issue or concern?

There will definitely be difference between two setting. If you use message in current batch, it will cause label leakage problems as written in the paper.

**Comment by emalgorithm** [comment]
Hi @wangywUST,

The difference is that if memory_update_at_start=False, then the memory will be updated with messages generated in the current batch, but there will be no gradient for all the memory related modules, as described in the paper.

This can be ok if using non-trainable modules, as it speeds up the model. However, if using modules which require training (as an GRU message updater), this method will not work (in the sense that you will not be able to learn these modules).

I hope this answers your question.

**Comment by Void-JackLee** [comment]
I have a similar question. When memory_update_at_start=True, the msg_agg and msg_func will calc twice, before the compute_embedding and after compute_embedding. Before the compute_embedding, the get_updated_memory function will calc all nodes' memory. After the compute_embedding, update_memory function will calc positive nodes. But if we just use the result of the first get_updated_memory function to update positive nodes' memory here, will this speed up the model without any influences? 

Maybe an image can be described more detailed.
![flow](https://github.com/twitter-research/tgn/assets/25055771/b4147d39-14d5-45fb-8770-24c11934777d)

**Comment by Void-JackLee** [comment]
Maybe an image can be described more detailed.
![flow](https://github.com/twitter-research/tgn/assets/25055771/b4147d39-14d5-45fb-8770-24c11934777d)
